version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  backend:
    container_name: backend
    build: ./
    command: bash -c "holdup tcp://db:5432 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/backend
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
      - PG_HOST=db

  cache:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save
    volumes:
      - cache:/data



volumes:
  cache:
    driver: local